# Generated by Django 4.1.6 on 2023-02-05 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='exercises',
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workout',
            name='uuid',
            field=models.UUIDField(default=1),
            preserve_default=False,
        ),
    ]
