# Generated by Django 4.1.6 on 2023-04-29 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
