# Generated by Django 4.1.6 on 2023-03-05 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_workout_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workout',
            old_name='user',
            new_name='use',
        ),
    ]
