# Generated by Django 4.1.6 on 2023-02-05 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_exercises_workout_workout_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='timestamp',
        ),
    ]
