# Generated by Django 4.1.6 on 2023-03-05 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_user_workout_use'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='use',
        ),
    ]
