# Generated by Django 4.1.6 on 2023-04-30 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_workout_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='duration',
        ),
    ]
