# Generated by Django 4.1.6 on 2023-05-01 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_workout_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='pr',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
    ]
