# Generated by Django 4.1.6 on 2023-03-07 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_meal_meal_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='image',
            field=models.ImageField(default='default.png', upload_to='meals'),
        ),
    ]
