# Generated by Django 4.1.6 on 2023-03-07 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_meal_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('os', models.CharField(choices=[('ANDROID', 'android'), ('IOS', 'ios')], max_length=10)),
                ('version', models.IntegerField(max_length=40)),
            ],
        ),
    ]
