# Generated by Django 4.1.6 on 2023-05-01 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_workout_pr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='workout_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
