# Generated by Django 4.1.6 on 2023-05-01 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_workout_workout_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='workout_data',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
    ]
