# Generated by Django 4.1.6 on 2023-03-07 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_version_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='os',
            field=models.CharField(choices=[('andriod', 'android'), ('ios', 'ios')], max_length=10),
        ),
    ]
