# Generated by Django 4.1.6 on 2023-03-07 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_version_os'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='os',
            field=models.CharField(choices=[('android', 'android'), ('ios', 'ios')], max_length=10),
        ),
    ]
