# Generated by Django 4.1.6 on 2023-03-07 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_workout_user'),
        ('api', '0009_alter_version_os'),
    ]

    operations = [
    ]
