# Generated by Django 4.1.6 on 2023-03-10 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_moment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tag',
            new_name='MealTag',
        ),
    ]
