# Generated by Django 4.1.6 on 2023-05-08 17:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_exercisefavorites_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='set',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
