# Generated by Django 4.1.6 on 2023-05-19 00:44

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_meal_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='recipe',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
