# Generated by Django 4.1.6 on 2023-06-07 05:48

import api.utils.image_utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_meal_recipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=api.utils.image_utils.generate_unique_filename),
        ),
        migrations.AlterField(
            model_name='meal',
            name='image',
            field=models.ImageField(default='default.png', upload_to='meals/<function generate_unique_filename at 0x7fc160e58d30>'),
        ),
    ]
