# Generated by Django 4.1.6 on 2023-06-21 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_meal_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='muscle_group',
            field=models.CharField(choices=[('Chest', 'Chest'), ('Back', 'Back'), ('Legs', 'Legs'), ('Shoulders', 'Shoulders'), ('Arms', 'Arms'), ('Abs', 'Abs')], default='Chest', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='meal',
            name='image',
            field=models.ImageField(default='default.png', upload_to='meals/<function generate_unique_filename at 0x7f3b14d76c10>'),
        ),
        migrations.AlterField(
            model_name='set',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.exercise'),
        ),
    ]
