version: '3.8'
services:
    web:
        tty: true
        stdin_open: true
        container_name: fitness_api
        build: .
        volumes:
            - .:/project
        ports:
            - 8000:8000
        depends_on:
            - db
      
    db:
        image: postgres
        container_name: fitness_db
        environment:
            POSTGRES_PASSWORD: postgres
        
        volumes:
            - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data: