# Generated by Django 4.1.6 on 2023-03-15 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_customuser_is_banned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ban',
            name='email',
        ),
        migrations.RemoveField(
            model_name='ban',
            name='ip',
        ),
    ]
