# Generated by Django 4.1.6 on 2023-03-15 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_ban_email_remove_ban_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ban',
            name='expiry_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='ban',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
