# Generated by Django 4.1.6 on 2023-04-24 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_profile_units'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='units',
        ),
        migrations.AddField(
            model_name='profile',
            name='units_height',
            field=models.CharField(choices=[('Metric', 'metric'), ('Imperial', 'imperial')], default='imperial', max_length=8),
        ),
        migrations.AddField(
            model_name='profile',
            name='units_weight',
            field=models.CharField(choices=[('Metric', 'metric'), ('Imperial', 'imperial')], default='imperial', max_length=8),
        ),
    ]
