# Generated by Django 4.1.6 on 2023-04-30 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_customuser_is_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_paid',
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='/avatar.jpg', null=True, upload_to='avatars'),
        ),
    ]
