# Generated by Django 4.1.6 on 2023-05-01 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_customuser_pr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='pr',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
