# Generated by Django 4.1.6 on 2023-05-09 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_customuser_is_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='show_workouts',
            field=models.BooleanField(default=False),
        ),
    ]
