# Generated by Django 4.1.6 on 2023-06-07 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_profile_birthdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='moments_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/<function generate_unique_filename at 0x7fc160e58d30>'),
        ),
    ]
