# Generated by Django 4.1.6 on 2023-06-12 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_profile_moments_count_alter_profile_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='units_height',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='units_weight',
        ),
        migrations.AddField(
            model_name='customuser',
            name='units_height',
            field=models.CharField(choices=[('metric', 'Metric'), ('imperial', 'Imperial')], default='imperial', max_length=8),
        ),
        migrations.AddField(
            model_name='customuser',
            name='units_weight',
            field=models.CharField(choices=[('metric', 'Metric'), ('imperial', 'Imperial')], default='imperial', max_length=8),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/<function generate_unique_filename at 0x7f204cb15d30>'),
        ),
    ]
