# Generated by Django 4.1.6 on 2023-06-12 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_remove_profile_units_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ban',
            name='ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/<function generate_unique_filename at 0x7fc53987bca0>'),
        ),
    ]
