# Generated by Django 4.1.6 on 2023-06-12 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_ban_ip_alter_profile_avatar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ban',
            old_name='expiry_date',
            new_name='expires',
        ),
        migrations.AddField(
            model_name='ban',
            name='permanent',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/<function generate_unique_filename at 0x7fa060323ca0>'),
        ),
    ]
