# Generated by Django 4.1.6 on 2023-06-21 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_rename_expiry_date_ban_expires_ban_permanent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/<function generate_unique_filename at 0x7f3b14d76c10>'),
        ),
    ]
